/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CrearSecuencias.java
 *
 * Created on 5/10/2010, 11:42:56 AM
 */

package interfaz;

import interfacebd.InterfaceBD;
import java.io.File;
import javax.swing.JFileChooser;
import utilerias.Procedimientos;
import utilerias.VariablesGlobales;

/**
 *
 * @author Administrador
 */
public class CrearBitacoras extends javax.swing.JFrame {

    InterfaceBD bd;

    /** Creates new form CrearSecuencias */
    public CrearBitacoras(InterfaceBD bd) {
        initComponents();
        pbBarra.setVisible(false);
        this.bd = bd;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsecutivo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        chkGenerarScripts = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txCarpetaDestino = new javax.swing.JTextField();
        btExaminar = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        btSiguiente = new javax.swing.JButton();
        pbBarra = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Secuencias");
        setResizable(false);

        chkGenerarScripts.setText("Generar archivo de Scripts");
        chkGenerarScripts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGenerarScriptsActionPerformed(evt);
            }
        });

        jLabel1.setText("Carpeta destino:");

        txCarpetaDestino.setEditable(false);

        btExaminar.setText("Examinar");
        btExaminar.setEnabled(false);
        btExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExaminarActionPerformed(evt);
            }
        });

        btRegresar.setFont(new java.awt.Font("Tahoma", 0, 10));
        btRegresar.setText("<Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        btSiguiente.setFont(new java.awt.Font("Tahoma", 0, 10));
        btSiguiente.setText("Crear");
        btSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkGenerarScripts, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCarpetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExaminar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pbBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(btSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(chkGenerarScripts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txCarpetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExaminar))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExaminarActionPerformed
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File rutaDir = null;
        if(!txCarpetaDestino.getText().equals("")){
            rutaDir = new File(txCarpetaDestino.getText().replace("\\", "\\\\"));
        }else if(new File("C:\\ARCHIVOS DE LUIS\\Archivos y documentos de LUIS\\NetBeans Projects\\").exists()){
            rutaDir = new File("C:\\ARCHIVOS DE LUIS\\Archivos y documentos de LUIS\\NetBeans Projects\\");
        }
        seleccionar.setCurrentDirectory(rutaDir);
        if(seleccionar.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            this.txCarpetaDestino.setText(seleccionar.getSelectedFile().getAbsolutePath());
            String paqueteClases = "";
            String [] elementos = seleccionar.getSelectedFile().getAbsolutePath().split("\\\\");
            if(elementos.length>=3){
                paqueteClases = elementos[elementos.length-3]+"."+elementos[elementos.length-2]+"."+elementos[elementos.length-1];
            }            
            String ruta = txCarpetaDestino.getText().replace("\\", "\\\\");
            VariablesGlobales.setRutaDestino(ruta);
        }
}//GEN-LAST:event_btExaminarActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        this.dispose();
        new SeleccionProceso(bd);
}//GEN-LAST:event_btRegresarActionPerformed

    private void btSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSiguienteActionPerformed
        Procedimientos proc = new Procedimientos(VariablesGlobales.getTablas());
        proc.setBd(bd);
        proc.setProc("bitacoras");
        Thread hilo = new Thread(proc);
        hilo.start();
}//GEN-LAST:event_btSiguienteActionPerformed

    private void chkGenerarScriptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGenerarScriptsActionPerformed
        btExaminar.setEnabled(chkGenerarScripts.isSelected());
        txCarpetaDestino.setText("");
    }//GEN-LAST:event_chkGenerarScriptsActionPerformed

    public InterfaceBD getBd() {
        return bd;
    }

    public void setBd(InterfaceBD bd) {
        this.bd = bd;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExaminar;
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btSiguiente;
    private javax.swing.ButtonGroup btnConsecutivo;
    private javax.swing.JCheckBox chkGenerarScripts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JProgressBar pbBarra;
    private javax.swing.JTextField txCarpetaDestino;
    // End of variables declaration//GEN-END:variables

    private void habilitarConsecutivos() {        
    }

}
